const newRecruitsChannel = 'new-recruits';
const testChannel = 'test-bot-discord-js';
const racePollChannel = 'race-poll';
const welcomeChannel = 'welcome';
const leagueInfoChannel = 'league-info';
const regulationsChannel = 'regulations';
const outChannel = 'out';
const formRegistrationsChannel = 'form-registrations';
const chatChannel = '🗣chat';

exports.newRecruitsChannel = newRecruitsChannel;
exports.testChannel = testChannel;
exports.racePollChannel = racePollChannel;
exports.welcomeChannel = welcomeChannel;
exports.regulationsChannel = regulationsChannel;
exports.leagueInfoChannel = leagueInfoChannel;
exports.outChannel = outChannel;
exports.formRegistrationsChannel = formRegistrationsChannel;
exports.chatChannel = chatChannel;